### ISSUE TITLE
Remove requests dependency

### ISSUE THREAD

**Issue by nrjones8** [rollbar/rollbar-agent#24]
`rollbar-agent` depends on the `requests` library, which (unfortunately) is not part of Python's standard library. As a result, the agent requires a virtual environment to run (or that the system-wide Python have `requests` installed).

It would be nice if the agent had no external dependencies, and was simply able to run right out of the box (without a `virtualenv` or anything else). Would you all be open to the idea of replacing `requests` with `urllib2`? It looks like `requests` is only used in [one place](https://github.com/rollbar/rollbar-agent/blob/master/rollbar-agent#L215), so the swap would be pretty simple. As a side note, I much prefer working with `requests` in general (it's a fantastic library!), but it does introduce the added complexity of a third party. 

Just a thought -- would love to hear your thoughts on this!

**Comment by brianr** [comment]
@coryvirok and I think this is a good idea. Happy to accept a PR :)

**Comment by nrjones8** [comment]
My only issue with it is that `urllib2` doesn't check SSL certificates by default, so there will need to be some extra logic added to do that. Python 2.7.9 added a simple `cafile` argument to [`urlopen`](https://docs.python.org/2/library/urllib2.html#urllib2.urlopen), but all previous versions don't have that. 

It would also probably make sense to include a CA file within this repo itself (could just use the one that [`requests` uses](https://github.com/kennethreitz/requests/blob/master/requests/cacert.pem)). Of course all of this is done for you by `requests`, which is one of the reasons that it's nice to have around :/

**Comment by coryvirok** [comment]
How about we take the route of trying to use `requests` if it is available and falling back to `urllib2` with a warning about not checking SSL certificates? We would also provide a config flag to explicitly use one or the other to quiet the warning.

**Comment by nrjones8** [comment]
Not sure if I'll personally get around to doing it soon, but seems like a reasonable approach!

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
