### ISSUE TITLE
Systemd support

### ISSUE THREAD

**Issue by passcod** [rollbar/rollbar-agent#26]
I see instructions and conf files for various init systems, but not systemd. Ubuntu, Fedora, Arch, and other Linuxen are already using and/or switching soon to Systemd, so it would be nice to have a systemd service file provided.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by passcod** [comment]
Both LTS versions of Ubuntu now use Systemd, as well as Fedora, Arch, Debian, Centos. The readme still shows instructions for an init.d file instead.

**Comment by fliespl** [comment]
Would be cool for it to be included :)
