### ISSUE TITLE
it is recommended to use synchronous reporting?

### ISSUE THREAD

**Issue by kidbrax** [rollbar/rollbar-agent#27]
According to the README, it is recommended to use synchronous reporting:

> In most cases you should try to use the Rollbar notifier for the language and framework you're using. See https://rollbar.com/docs for a list of supported languages and links to notifiers.

And per the rollbar-php README:

> This is easy to configure but may negatively impact performance.

But if that impacts performance, why wouldn't you recommend using the agent?

**Comment by brianr** [comment]
@kidbrax , thanks for bringing this up! We definitely intend to recommend async reporting across all platforms. Most provide other, easier ways to achieve this, except for PHP.

I've updated the readme to make this, hopefully, more clear. Let me know what you think.

https://github.com/rollbar/rollbar-agent/commit/4e5d0f5ac4330d55639ca91e11df18c96777c888

**Comment by kidbrax** [comment]
@brianr much better, thanks!
