### ISSUE TITLE
Multiple domains on the same server

### ISSUE THREAD

**Issue by anthropos9** [rollbar/rollbar-agent#29]
We're trying to roll out Rollbar across several domains that are all on the same server. Is there a way to set up the agent to know which domain is reporting or do we need to set up multiple agents - one per api key? If we need to set up several, is the `virtualenv` the key to getting it to work? Thanks.

**Comment by rokob** [comment]
So looking at the rollbar-agent code, it looks like you can define multiple `apps` in the configuration file using sections, for example:

```
[app:myapp]
# rollbar project access token
params.access_token = 32characterstring
targets = /path/to/log/dir1
    /path/to/log/dir2
    /path/to/log/dir3

[app:otherapp]
# rollbar project access token
params.access_token = maybeDifferentMaybeTheSame
targets = /path/to/otherapp/log/dir1
    /path/to/otherapp/log/dir2
    /path/to/otherapp/log/dir3
```

This name for the app ends up in the notifier data attached to the payload with key `rollbar_agent_app`.

I am a little unclear what you are doing though so I am not sure where to point you from there. Are you logging to the same log files for multiple domains? If it is possible to pipe your logs to different files based on domain, then you can use the above to pick up the different files for the different apps and things should be separated a bit that way. Ideally you should only have to run one agent if you want to go the agent route so if this won't work then we should figure out a way to add some configuration options that work for you.

All that said, the language specific notifier libraries are the easier way to get data into Rollbar and this agent should ideally only be a last resort.

**Comment by anthropos9** [comment]
Thanks for the response. I'll try your suggestions and get back to you

**Comment by anthropos9** [comment]
The agent is running now and it seems to be consuming the log files created - using the PHP notifier library. The notifier creates the logs and the agent seems to consume them then delete them, but it looks like it's still the notifier that's sending the information to rollbar.com. I'm not seeing ```rollbar_agent_app``` anywhere in the raw request on rollbar.com. Any ideas what I could have missed? Thanks.

**Comment by rokob** [comment]
The php notifier generates log files with filenames like `something.828392893.rollbar`. The agent considers files of the type `.rollbar` to be special in how they are processed. Those files contain lines which are fully formed payloads ready to be sent to the API. Therefore the agent just sends the payload as-is, modulo adding an access token if one is missing. Hence, the notifier name is already set by rollbar-php in the payload, so you would not see anything about the agent in the raw payloads.

Using the agent as the payload sending mechanism is more of an implementation detail of the transport layer for rollbar-php. The agent does not actually do much work in that case. What you are seeing is as expected.
