### ISSUE TITLE
Rollbar-agent: Need a way to mute "INFO scanner thread looping..."

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-agent#30]
Details in https://app.clubhouse.io/rollbar/story/15497/rollbar-agent-need-a-way-to-mute-info-scanner-thread-looping

**Comment by corps** [comment]
FYI:  Although cumbersome, one can always `&> /dev/null` if you need completely silent processing.

**Comment by rivkahstandig3636** [comment]
Thanks @corps!

**Comment by rokob** [comment]
The quiet option already exists:

```
590     verbosity.add_option('-q', '--quiet', dest='quiet', action='store_true', default=False,
591         help='Quiet output (uses log level WARNING)')
```

To use it with a service edit the args in the init script at https://github.com/rollbar/rollbar-agent/blob/master/rollbar-agent-init.sh#L22 to include `--quiet` to only output warnings. The `scanner thread looping...` message is at the default info level.

I consider this to be sufficient for the purpose of this issue so going to close.
