### ISSUE TITLE
Config parameter: max_file_age 

### ISSUE THREAD

**Issue by MetalGuardian** [rollbar/rollbar-agent#34]
Hi there!
There is a block in the agent config:
```
# don't examine files older than this
# set to 0 for no max
max_file_age = 86400
```
But I can't find any place in the agent code where is it used.
Plus in the `parse_config` function there is a line
```
'max_file_page': to_int,
``` 
but anyway this `max_file_page` is not used further in the code.

Is this config parameter in use?

**Comment by brianr** [comment]
Hi @MetalGuardian - thanks for the report... looks like this param has not actually been implemented. I've just removed it from the example config file in https://github.com/rollbar/rollbar-agent/commit/23cf28d61732fd3f251bfdf9368b796dfa4b86e9
