### ISSUE TITLE
Log rotation that uses 'copytruncate' not detected by agent

### ISSUE THREAD

**Issue by ugwjames** [rollbar/rollbar-agent#37]
The inode of files rotated in this method does not change (and the same file is used, and only the contents are coped to a backup).

Locally I have a working test that uses the file size (`size = stats[stat.ST_SIZE]`) and then adds that to the rotation check: `if inode != files_state[filename]['inode']:` -> `if inode != files_state[filename]['inode'] or files_state[filename]['pos'] > size:`

I am unsure if this creates other risks or issues.

**Comment by corps** [comment]
This will work in most cases.  The potential risk is the race condition that a file may be rotated, and written to, exceeding the previous position, before rollbar-agent runs again.  In this case, rollbar-agent will assume that nothing has changed (it can't tell that copytruncate has occurred if the file size grows faster than its current offset, afterall) and you will loose logs.

This is one reason it is not safe to do this in the general case, but it may acceptable if your logs are slow moving or you don't mind missing data.

**Comment by ugwjames** [comment]
Ok, that makes perfect sense, I will keep this condition in mind as we test this.  We may switch from daily rotation to file size based rotation to keep the chance of this happening even lower.
