### ISSUE TITLE
Package rollbal-agent for Debian/Ubuntu

### ISSUE THREAD

**Issue by gnarea** [rollbar/rollbar-agent#4]
It'd be extremely useful to us if you offered .deb packages for Debian and/or Ubuntu.

Even better if you offered a deb repository.

Cheers.

**Comment by elopio** [comment]
Debian and Ubuntu now support snaps: https://snapcraft.io/
That would be a quick alternative to get the agent into the existing releases. I gave it a quick try and https://github.com/rollbar/rollbar-agent/pull/28 has a yaml that can help you getting started. It requires more testing, obviously.

Let me know if publishing a snap sounds interesting to you :)

**Comment by rokob** [comment]
We recently merged a PR that should allow one to build a snap which should address building the package. I can look into building out a debian package if that is not sufficient.

**Comment by jessewgibbs** [comment]
I'm going to close this due to age.
