### ISSUE TITLE
Error with Exceptions

### ISSUE THREAD

**Issue by Gildus** [rollbar/rollbar-agent#47]
I try install with pip with all configurations and it return the error:

>   File "/usr/local/rollbar-agent", line 317
>     except Exception, e:
> 

https://github.com/rollbar/rollbar-agent/blob/master/rollbar-agent#L317

I'm using:
- python 3.6.8
- pip 19.1.1

**Comment by Gildus** [comment]
I think don't work with python 3.6.8 :face_with_head_bandage:

**Comment by dbaggott** [comment]
Python 3 is not currently supported (https://github.com/rollbar/rollbar-agent/issues/53 and https://github.com/rollbar/rollbar-agent/issues/54)

**Comment by bxsx** [comment]
Hey @Gildus @dbaggott  

Happy to announce that we just released a new `v0.5.0` version of Rollbar-Agent that supports Python 3.
