### ISSUE TITLE
Update documentation to clarify lack of Python 3 support

### ISSUE THREAD

**Issue by dbaggott** [rollbar/rollbar-agent#53]
The README says the agent requires Python 2.6+  However, it appear that the syntax used in the code is not compatible with Python 3.

The first thing it blows up on when you try to run with Python 3 is the except syntax (https://portingguide.readthedocs.io/en/latest/exceptions.html#the-new-except-syntax)

Output from the logs when Python 3.9.0 is used:

```
  File "/apps/rollbar-agent/venv/rollbar-agent", line 321
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

Please update documentation to clarify python version requirements.

**Comment by bxsx** [comment]
Hey @dbaggott 

Happy to announce that we just released a new `v0.5.0` version of Rollbar-Agent that supports Python 3.
