### ISSUE TITLE
Support running agent on Python 3

### ISSUE THREAD

**Issue by dbaggott** [rollbar/rollbar-agent#54]
The rollbar-agent does not run on Python 3 (see https://github.com/rollbar/rollbar-agent/issues/53).

Python 2 has been officially sunsetted and is no longer supported, does not receive security patches, etc (see https://www.python.org/doc/sunset-python-2/)

**Comment by bxsx** [comment]
Hey @dbaggott 

Happy to announce that we just released a new `v0.5.0` version of Rollbar-Agent that supports Python 3.

**Comment by dbaggott** [comment]
@bxsx, great, glad to hear it!
