### ISSUE TITLE
multiple spaces between "log_format.patterns" key/value pair in rollbar-agent.conf causes failure

### ISSUE THREAD

**Issue by colinbjohnson** [rollbar/rollbar-agent#7]
example:

```
log_format.patterns =
    *.log  myapp
```

will cause:

```
File "/srv/c_python/virtualenv/c_rollbar_agent/rollbar-agent", line 281, in process
    log.debug("File %s using parser %s", filename, parser['name'])
```

No spaces in front of the regex key also creates a problem:

example:

```
log_format.patterns =
*.log  myapp
```

will cause:

```
ConfigParser.ParsingError: File contains parsing errors: /etc/rollbar-agent.conf
    [line 47]: '*.log myapp\n'
```

I might find some time to submit a fix myself but I wanted to file in event someone else runs into same problem.

**Comment by rokob** [comment]
Reading the docs for ConfigParser which we use to parse the config file, https://docs.python.org/2/library/configparser.html, it uses the longer header formatting rules from https://tools.ietf.org/html/rfc822.html. Hence, not having a space at the beginning of the line to represent a continuation is not supported. We would have to use a different configuration file parser to be able to handle that and that seems unreasonable. We can add some docs to that part of the example config file to clearly say that the leading whitespace is necessary.

As to handling multiple spaces between the glob and the format name that is a simple fix, will link the PR for that shortly.
