### ISSUE TITLE
support providing LOG_LEVEL through configuration file

### ISSUE THREAD

**Issue by colinbjohnson** [rollbar/rollbar-agent#8]
it would be awesome if the LOG_LEVEL could be set on a per app basis - we don't need that for our use case, however. I will try and provide a pull request that gets LOG_LEVEL from a configuration file this afternoon, as this would be helpful to us.

**Comment by rokob** [comment]
https://github.com/rollbar/rollbar-agent/commit/715a936e0fec807ea25d3b3df05dec32d3d99c66
